ruby script/generate model attack_spells
ruby script/generate model base_items
ruby script/generate model blacksmith_skills
ruby script/generate model boards
ruby script/generate model class_levels
ruby script/generate model classes
ruby script/generate model creature_kills
ruby script/generate model creatures
ruby script/generate model diseases
ruby script/generate model done_events
ruby script/generate model done_quests
ruby script/generate model event_creatures
ruby script/generate model event_diseases
ruby script/generate model event_items
ruby script/generate model event_moves
ruby script/generate model event_npcs
ruby script/generate model event_players
ruby script/generate model event_quests
ruby script/generate model event_stats
ruby script/generate model events
ruby script/generate model feature_events
ruby script/generate model features
ruby script/generate model genocides
ruby script/generate model healer_skills
ruby script/generate model healing_spells
ruby script/generate model images
ruby script/generate model infections
ruby script/generate model items
ruby script/generate model kingdom_bans
ruby script/generate model kingdom_entries
ruby script/generate model kingdom_items
ruby script/generate model kingdom_maps
ruby script/generate model kingdom_notices
ruby script/generate model kingdoms
ruby script/generate model level_maps
ruby script/generate model levels
ruby script/generate model log_quest_creature_kills
ruby script/generate model log_quest_explores
ruby script/generate model log_quest_kill_n_npcs
ruby script/generate model log_quest_kill_pcs
ruby script/generate model log_quest_kill_s_npcs
ruby script/generate model log_quests
ruby script/generate model nonplayer_killers
ruby script/generate model npc_blacksmith_items
ruby script/generate model npc_diseases
ruby script/generate model npc_merchants
ruby script/generate model npc_stocks
ruby script/generate model npcs
ruby script/generate model pandemics
ruby script/generate model player_characters
ruby script/generate model player_equip_locs
ruby script/generate model player_items
ruby script/generate model player_killers
ruby script/generate model players
ruby script/generate model posts
ruby script/generate model quest_creature_kills
ruby script/generate model quest_explores
ruby script/generate model quest_items
ruby script/generate model quest_kill_n_npcs
ruby script/generate model quest_kill_pcs
ruby script/generate model quest_kill_s_npcs
ruby script/generate model quests
ruby script/generate model race_equip_locs
ruby script/generate model race_levels
ruby script/generate model races
ruby script/generate model special_codes
ruby script/generate model threads
ruby script/generate model trainer_skills
ruby script/generate model world_maps
ruby script/generate model worlds
