ruby script/generate scaffold admin/attack_spell
ruby script/generate scaffold admin/base_item
ruby script/generate scaffold admin/blacksmith_skill
ruby script/generate scaffold admin/board
ruby script/generate scaffold admin/c_class_level
ruby script/generate scaffold admin/c_class
ruby script/generate scaffold admin/creature_kill
ruby script/generate scaffold admin/creature
ruby script/generate scaffold admin/disease
ruby script/generate scaffold admin/done_event
ruby script/generate scaffold admin/done_quest
ruby script/generate scaffold admin/event_creature
ruby script/generate scaffold admin/event_disease
ruby script/generate scaffold admin/event_item
ruby script/generate scaffold admin/event_move
ruby script/generate scaffold admin/event_npc
ruby script/generate scaffold admin/event_player_character
ruby script/generate scaffold admin/event_quest
ruby script/generate scaffold admin/event_stat
ruby script/generate scaffold admin/event
ruby script/generate scaffold admin/feature_event
ruby script/generate scaffold admin/feature
ruby script/generate scaffold admin/genocide
ruby script/generate scaffold admin/healer_skill
ruby script/generate scaffold admin/healing_spell
ruby script/generate scaffold admin/image
ruby script/generate scaffold admin/infection
ruby script/generate scaffold admin/item
ruby script/generate scaffold admin/kingdom_ban
ruby script/generate scaffold admin/kingdom_entry
ruby script/generate scaffold admin/kingdom_item
ruby script/generate scaffold admin/kingdom_notice
ruby script/generate scaffold admin/kingdom
ruby script/generate scaffold admin/level_map
ruby script/generate scaffold admin/level
ruby script/generate scaffold admin/log_quest_creature_kill
ruby script/generate scaffold admin/log_quest_explore
ruby script/generate scaffold admin/log_quest_kill_n_npc
ruby script/generate scaffold admin/log_quest_kill_pc
ruby script/generate scaffold admin/log_quest_kill_s_npc
ruby script/generate scaffold admin/log_quest
ruby script/generate scaffold admin/nonplayer_character_killer
ruby script/generate scaffold admin/npc_blacksmith_item
ruby script/generate scaffold admin/npc_disease
ruby script/generate scaffold admin/npc_merchant
ruby script/generate scaffold admin/npc_stock
ruby script/generate scaffold admin/npc
ruby script/generate scaffold admin/pandemic
ruby script/generate scaffold admin/player_character
ruby script/generate scaffold admin/player_character_equip_loc
ruby script/generate scaffold admin/player_character_item
ruby script/generate scaffold admin/player_character_killer
ruby script/generate scaffold admin/player
ruby script/generate scaffold admin/post
ruby script/generate scaffold admin/quest_creature_kill
ruby script/generate scaffold admin/quest_explore
ruby script/generate scaffold admin/quest_item
ruby script/generate scaffold admin/quest_kill_n_npc
ruby script/generate scaffold admin/quest_kill_pc
ruby script/generate scaffold admin/quest_kill_s_npc
ruby script/generate scaffold admin/quest
ruby script/generate scaffold admin/race_equip_loc
ruby script/generate scaffold admin/race_level
ruby script/generate scaffold admin/race
ruby script/generate scaffold admin/special_code
ruby script/generate scaffold admin/thred
ruby script/generate scaffold admin/trainer_skill
ruby script/generate scaffold admin/world_map
ruby script/generate scaffold admin/world
